version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "9000:80"
    environment:
      PMA_HOST: db
      PMA_PASSWORD: password
